Repository graasp/graasp-deploy, pull requests merged in 2023-03, with the labels that each got.

#134 feat: add composite workflow for s3 deploy
  .github/actions/deploy-s3-app/action.yml
  .github/actions/deploy-s3/action.yml
  .github/workflows/cypress.yml
Labels: chore, ci

#180 fix: add recaptcha key
  .github/workflows/cdelivery-s3.yml
  .github/workflows/cdeployment-s3.yml
  .github/workflows/cintegration-s3.yml
Labels: priority

#181 chore: bump graasp to 0.6.1
  staging-versions/latest.json
Labels: bug, chore
