Repository graasp/graasp-deploy, pull requests merged in 2023-01, with the labels that each got.

#141 fix: step summary with tag
  .github/workflows/update-staging-stack.yml
Labels: bug

#143 feat: add etherpad env vars
  .github/workflows/cdelivery-ecs-backend.yml
  .github/workflows/cdeployment-ecs-backend.yml
  .github/workflows/cintegration-ecs-backend.yml
Labels: feature

#147 feat: add etherpad cookie domain input
  .github/workflows/cdelivery-ecs-backend.yml
  .github/workflows/cdeployment-ecs-backend.yml
  .github/workflows/cintegration-ecs-backend.yml
Labels: feature

#119 feat: add analytics host to library workflows
  .github/workflows/cdelivery-ecs-library.yml
  .github/workflows/cdeployment-ecs-library.yml
  .github/workflows/cintegration-ecs-library.yml
  .github/workflows/cypress.yml
Labels: feature

#155 feat: add sentry DSN secret
  .github/workflows/cdelivery-ecs-backend.yml
  .github/workflows/cdeployment-ecs-backend.yml
  .github/workflows/cintegration-ecs-backend.yml
Labels: feature

#153 feat: split secrets and env vars in deployment workflows
  .github/workflows/cdelivery-ecs-backend.yml
  .github/workflows/cdeployment-ecs-backend.yml
  .github/workflows/cintegration-ecs-backend.yml
Labels: build

#159 fix: remove legacy ga env vars
  .github/workflows/cdelivery-ecs-library.yml
  .github/workflows/cdeployment-ecs-library.yml
  .github/workflows/cintegration-ecs-library.yml
  .github/workflows/update-staging-stack.yml
Labels: bug, chore
